/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.19
 * Generated at: 2024-03-17 17:20:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class uitlening_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Book Overview</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"book.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <img src=\"tech.jpg\" alt=\"Logo\">\r\n");
      out.write("\r\n");
      out.write("        <nav>\r\n");
      out.write("            <a href=\"index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"boek.jsp\">Books</a>\r\n");
      out.write("            <a href=\"user.jsp\">Users</a>\r\n");
      out.write("            <a href=\"uitlening.jsp\">Uitlening</a>\r\n");
      out.write("            <a href=\"about.jsp\">About</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <h1 style=\"color: #fff;\">Uitlening Overview</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 text-md-end\">\r\n");
      out.write("                <button id=\"createBookBtn\" class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#createUitleningModal\">Create Uitlening</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>ID</th>\r\n");
      out.write("                    <th>User</th>\r\n");
      out.write("                    <th>Boek</th>\r\n");
      out.write("                    <th>Uitlening</th>\r\n");
      out.write("                    <th>Terug gebracht</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody id=\"UitleningTableBody\"></tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"btn btn-primary\" onclick=\"goToIndex()\">Back to Index</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Edit Book Modal -->\r\n");
      out.write("    <div class=\"modal\" id=\"editUitleningModal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\">Edit Book</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-bs-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("\r\n");
      out.write("                 <!-- Book edit form -->\r\n");
      out.write("                    <form id=\"editUitleningForm\">\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"editNaam\">Naam:</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"editNaam\" name=\"editNaam\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"editBoek\">Boek:</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"editBoek\" name=\"editBoek\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-group\">\r\n");
      out.write("                            <label for=\"editUitlening\">Uitlening:</label>\r\n");
      out.write("                            <input type=\"number\" class=\"form-control\" id=\"editUitlening\" name=\"editUitlening\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                          <div class=\"form-group\">\r\n");
      out.write("                             <label for=\"editTerugGebracht\">Terug Gebracht:</label>\r\n");
      out.write("                             <input type=\"number\" class=\"form-control\" id=\"editTerugGebracht\" name=\"editTerugGebracht\" required>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                        <input type=\"hidden\" id=\"uitleningID\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-primary\" onclick=\"saveUitleningChanges()\">Update</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Confirmation Modal -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"confirmationModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"confirmationModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"confirmationModalLabel\">Confirm Deletion</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-bs-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <p>Are you sure you want to delete this Book?</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-danger\" id=\"confirmDeleteBtn\">Delete</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   <!-- Create Uitlening Modal -->\r\n");
      out.write("   <div class=\"modal\" id=\"createUitleningModal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("       <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("           <div class=\"modal-content\">\r\n");
      out.write("               <div class=\"modal-header\">\r\n");
      out.write("                   <h5 class=\"modal-title\">Create Uitlening</h5>\r\n");
      out.write("                   <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"modal-body\">\r\n");
      out.write("                   <form id=\"createUitleningForm\">\r\n");
      out.write("                       <div class=\"form-group\">\r\n");
      out.write("                           <label for=\"createNaam\">Gebruiker:</label>\r\n");
      out.write("                           <select class=\"form-control\" id=\"createNaam\" name=\"createNaam\" required>\r\n");
      out.write("                               <!-- Opties worden hier dynamisch toegevoegd -->\r\n");
      out.write("                           </select>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       <div class=\"form-group\">\r\n");
      out.write("                           <label for=\"createBoek\">Boek:</label>\r\n");
      out.write("                           <select class=\"form-control\" id=\"createBoek\" name=\"createBoek\" required>\r\n");
      out.write("                               <!-- Opties worden hier dynamisch toegevoegd -->\r\n");
      out.write("                           </select>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       <div class=\"form-group\">\r\n");
      out.write("                           <label for=\"createUitlening\">Uitlening:</label>\r\n");
      out.write("                           <input type=\"date\" class=\"form-control\" id=\"createUitlening\" name=\"createUitlening\" required>\r\n");
      out.write("                       </div>\r\n");
      out.write("                       <button type=\"button\" class=\"btn btn-success\" onclick=\"saveUitlening()\">Save</button>\r\n");
      out.write("                   </form>\r\n");
      out.write("               </div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"alertPlaceholder\"></div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"uitlening.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        function goToIndex() {\r\n");
      out.write("            window.location.href = 'http://localhost:8080/api/';\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
